In [1]:
import torch
print(torch.__version__)

2.7.1+cpu


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
else:
    print("CPU is available")

CPU is available


# Creating a Tensor

In [13]:
#Creates space for it, 
# assigns already existing values in the memory
a=torch.empty(2,3) 
print(a)
print(type(a))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [10]:
a=torch.zeros(2,3)
b=torch.ones(2,3)
print(a)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
torch.rand(2,3)

tensor([[0.0611, 0.3994, 0.9054],
        [0.2545, 0.5907, 0.1022]])

In [15]:
# Manual seed is used fro reproducibility 
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [18]:
# Making a custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [39]:
# Other methods
print("Using arange:", torch.arange(0,10,2)) #0-9, step=2
print("Using linspace:", torch.linspace(0,10,10)) #0-9, linearly spaced values between 0-10
print(torch.eye(5)) # Creates identity matrix
print(torch.full((3,3),5)) # Creates a matrix with all elements as a desired value

Using arange: tensor([0, 2, 4, 6, 8])
Using linspace: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [5]:
import torch
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [24]:
print(torch.empty_like(x)) 
# Creates an empty tensor having same shape as x
# All elements need not be zero
print(torch.zeros_like(x))
print(torch.ones_like(x))
# torch.rand_like(x) not working
# because values in x are all integers & rand function 
# initialises all elements to floats between 0-1
print(torch.rand_like(x,dtype=torch.float32))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.0839, 0.2853, 0.2997],
        [0.4604, 0.5977, 0.6602]])


# Tensor Data Types

In [16]:
# Find data types
x.dtype

torch.int64

In [15]:
# Assign data types
print(torch.tensor([1.0,2.0,3.0], dtype=torch.int32))
print(torch.tensor([1,2,3], dtype=torch.float64))

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.], dtype=torch.float64)


In [19]:
print(x)
x.to(torch.float32) # Convert an existing tensor

tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical operations
## Scalar operations

In [26]:
x=torch.rand(2,2)
x

tensor([[0.9168, 0.7618],
        [0.2511, 0.2503]])

In [30]:
print(x+2)
print(x-2)
print(x*3)
print(x/3)
print((x*100)//3) # Integer division
print(((x*100)//3)%2) # Remainder
print(x**2)

tensor([[2.9168, 2.7618],
        [2.2511, 2.2503]])
tensor([[-1.0832, -1.2382],
        [-1.7489, -1.7497]])
tensor([[2.7504, 2.2855],
        [0.7533, 0.7509]])
tensor([[0.3056, 0.2539],
        [0.0837, 0.0834]])
tensor([[30., 25.],
        [ 8.,  8.]])
tensor([[0., 1.],
        [0., 0.]])
tensor([[0.8405, 0.5804],
        [0.0631, 0.0626]])


## Element wise operations

In [31]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.0861, 0.9664, 0.1839],
        [0.2417, 0.3533, 0.5686]])
tensor([[0.6366, 0.9329, 0.8258],
        [0.8322, 0.0996, 0.2356]])


In [34]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a%b)

tensor([[0.7227, 1.8993, 1.0097],
        [1.0738, 0.4530, 0.8042]])
tensor([[-0.5505,  0.0336, -0.6419],
        [-0.5905,  0.2537,  0.3330]])
tensor([[0.0548, 0.9015, 0.1519],
        [0.2011, 0.0352, 0.1340]])
tensor([[0.1352, 1.0360, 0.2227],
        [0.2904, 3.5472, 2.4132]])
tensor([[0.2099, 0.9686, 0.2470],
        [0.3067, 0.9016, 0.8754]])
tensor([[0.0861, 0.0336, 0.1839],
        [0.2417, 0.0545, 0.0974]])


In [37]:
c=torch.tensor([1,-2,3,-4])
print(torch.abs(c))
print(torch.neg(c))

tensor([1, 2, 3, 4])
tensor([-1,  2, -3,  4])


In [40]:
d=torch.tensor([1.9,2.3,3.7,4.4])
print(torch.round(d))
print(torch.ceil(d))
print(torch.floor(d))
print(torch.clamp(d, min=2, max=3))

tensor([2., 2., 4., 4.])
tensor([2., 3., 4., 5.])
tensor([1., 2., 3., 4.])
tensor([2.0000, 2.3000, 3.0000, 3.0000])


## Reduction Operations

In [44]:
e=torch.randint(size=(2,3),low=0,high=10, 
                dtype=torch.float32)
e

tensor([[4., 4., 8.],
        [7., 5., 3.]])

In [51]:
# sum
print(torch.sum(e))
# sum along columns
print(torch.sum(e, dim=0))
# sum along rows
print(torch.sum(e, dim=1))
print(torch.mean(e))
print(torch.mean(e, dim=0)) # mean along column
print(torch.median(e))
print(torch.min(e))
print(torch.max(e))
print(torch.prod(e)) # product
print(torch.std(e)) # standard deviation
print(torch.var(e)) # variance
print(torch.argmax(e)) # position of the largest element
print(torch.argmin(e)) # position of the smallest element

tensor(31.)
tensor([11.,  9., 11.])
tensor([16., 15.])
tensor(5.1667)
tensor([5.5000, 4.5000, 5.5000])
tensor(4.)
tensor(3.)
tensor(8.)
tensor(13440.)
tensor(1.9408)
tensor(3.7667)
tensor(2)
tensor(5)


## Matrix operations

In [60]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)
print(torch.matmul(f,g)) #matrix multiplication

tensor([[8, 1, 7],
        [4, 9, 0]])
tensor([[4, 2],
        [8, 1],
        [8, 7]])
tensor([[96, 66],
        [88, 17]])


In [62]:
v1=torch.tensor([1,2])
v2=torch.tensor([3,4])
torch.dot(v1,v2)

tensor(11)

In [73]:
A=torch.randint(size=(2,3),low=0,high=10)
print(A)
print(torch.transpose(A,0,1))

tensor([[3, 4, 1],
        [6, 6, 2]])
tensor([[3, 6],
        [4, 6],
        [1, 2]])


In [78]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(h)
print(torch.det(h))
print(torch.inverse(h))

tensor([[7., 6., 4.],
        [1., 0., 8.],
        [0., 5., 2.]])
tensor(-272.)
tensor([[ 0.1471, -0.0294, -0.1765],
        [ 0.0074, -0.0515,  0.1912],
        [-0.0184,  0.1287,  0.0221]])


## Comparison Operations

In [79]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[5, 0, 0],
        [7, 2, 2]])
tensor([[4, 6, 4],
        [9, 9, 0]])


In [82]:
print(i>j)
print(i<j)
print(i==j)
print(i!=j)
print(i<=j)
print(i>=j)

tensor([[ True, False, False],
        [False, False,  True]])
tensor([[False,  True,  True],
        [ True,  True, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False,  True,  True],
        [ True,  True, False]])
tensor([[ True, False, False],
        [False, False,  True]])


## Special functions

In [90]:
k=torch.randint(size=(2,3),low=0,high=10, dtype=torch.float32)
print(k)

tensor([[2., 4., 5.],
        [4., 6., 9.]])


In [91]:
print(torch.log(k))
print(torch.exp(k))
print(torch.sqrt(k))
print(torch.sigmoid(k))
print(torch.softmax(k, dim=0))
print(torch.relu(k))

tensor([[0.6931, 1.3863, 1.6094],
        [1.3863, 1.7918, 2.1972]])
tensor([[7.3891e+00, 5.4598e+01, 1.4841e+02],
        [5.4598e+01, 4.0343e+02, 8.1031e+03]])
tensor([[1.4142, 2.0000, 2.2361],
        [2.0000, 2.4495, 3.0000]])
tensor([[0.8808, 0.9820, 0.9933],
        [0.9820, 0.9975, 0.9999]])
tensor([[0.1192, 0.1192, 0.0180],
        [0.8808, 0.8808, 0.9820]])
tensor([[2., 4., 5.],
        [4., 6., 9.]])


## Inplace Operattions
Makes changes in the existing tensor without creating a new one & thereby not occupying extra memory for each simple operation.
It can be achieved by just putting an underscore after the function name.

In [92]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.8068, 0.1770, 0.3479],
        [0.1735, 0.5253, 0.0910]])
tensor([[0.9471, 0.9906, 0.3506],
        [0.5143, 0.1314, 0.5857]])


In [94]:
m.add_(n)
print(m)
print(n)

tensor([[2.7009, 2.1582, 1.0491],
        [1.2021, 0.7881, 1.2623]])
tensor([[0.9471, 0.9906, 0.3506],
        [0.5143, 0.1314, 0.5857]])


# Copying a tensor

In [107]:
a=torch.rand(2,3)
a

tensor([[0.0721, 0.0408, 0.6237],
        [0.7990, 0.4897, 0.9312]])

In [108]:
b=a.clone() # Forms a clone at new memory location
a[0][0]=1
print(a)
print(b)

tensor([[1.0000, 0.0408, 0.6237],
        [0.7990, 0.4897, 0.9312]])
tensor([[0.0721, 0.0408, 0.6237],
        [0.7990, 0.4897, 0.9312]])


# Tesnor Operations on GPU

In [109]:
torch.cuda.is_available()

False

# Reshaping Tensors

In [110]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [111]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [112]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [113]:
b=torch.rand(2,3,4)
b

tensor([[[0.0614, 0.3468, 0.7133, 0.3868],
         [0.7816, 0.8005, 0.3011, 0.9744],
         [0.9520, 0.5579, 0.9522, 0.7523]],

        [[0.3403, 0.4381, 0.1202, 0.9815],
         [0.3996, 0.2926, 0.1090, 0.4209],
         [0.1095, 0.4564, 0.8049, 0.1937]]])

In [117]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [123]:
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [124]:
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy & PyTorch

In [125]:
import numpy as np

In [133]:
a=torch.tensor([1,2,3])
type(a)

torch.Tensor

In [132]:
b=a.numpy()
type(b)

numpy.ndarray

In [137]:
c=np.array([4,5,6])
print(c)
type(c)

[4 5 6]


numpy.ndarray

In [136]:
d=torch.from_numpy(c)
print(d)
type(d)

tensor([4, 5, 6])


torch.Tensor

# Autograd
It is a core component of PyTorch that provides automatic diffferentiation for tensor operations. It enables gradient computation, which is essential for training machine learning models using optimisation algorithms like gradient descent.

## Example 1: y=x^2

In [1]:
import torch

In [2]:
x=torch.tensor(3.0, requires_grad=True)
y=x**2

In [3]:
print(x)
print(y)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)


In [4]:
y.backward()

In [5]:
x.grad

tensor(6.)

## Example 2: y=x^2, z=sin(y)

In [6]:
x=torch.tensor(3.0, requires_grad=True)
y=x**2
z=torch.sin(y)

In [7]:
print(x)
print(y)
print(z)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)
tensor(0.4121, grad_fn=<SinBackward0>)


In [8]:
z.backward()

In [9]:
x.grad

tensor(-5.4668)

Input is called leaf tensor & output is called root tensor. In backward pass the derivative of root tensor with respect to the leaf tensor is calculated.

## Example 3: Placement & CGPA NN

### Manually doing without Autograd:

In [1]:
import torch

# Inputs
x=torch.tensor(6.7) # Input feature
y=torch.tensor(0.0) # True label (binary)

w=torch.tensor(1.0) # weight
b=torch.tensor(0.0) # bias

In [8]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon=1e-8 # To prevent log(0)
    prediction=torch.clamp(prediction, epsilon, 1-epsilon)
    return -(target*torch.log(prediction)+(1-target)*torch.log(1-prediction))

# Forward pass
z=w*x+b # Weighteed sum (linear part)
y_pred=torch.sigmoid(z) # Predicited probability

# Compute binary cross entropy loss
loss=binary_cross_entropy_loss(y_pred, y)

In [9]:
loss

tensor(6.7012)

In [10]:
# Derivatives
# 1. 
dloss_dy_pred=(y_pred-y)/(y_pred*(1-y_pred))
# 2.
dy_pred_dz=y_pred*(1-y_pred)
# 3.
dz_dw=x
dz_db=1

dL_dw=dloss_dy_pred*dy_pred_dz*dz_dw
dL_db=dloss_dy_pred*dy_pred_dz*dz_db

In [11]:
print(f"Manual gradient of loss w.r.t. weight (dw): {dL_dw}")
print(f"Manual gradient of loss w.r.t. bias (db): {dL_db}")

Manual gradient of loss w.r.t. weight (dw): 6.691762447357178
Manual gradient of loss w.r.t. bias (db): 0.998770534992218


### Using Autograd:

In [13]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)
w=torch.tensor(1.0, requires_grad=True)
b=torch.tensor(0.0, requires_grad=True)

In [14]:
print(w,b)

tensor(1., requires_grad=True) tensor(0., requires_grad=True)


In [15]:
z=w*x+b
print(z)

tensor(6.7000, grad_fn=<AddBackward0>)


In [16]:
y_pred=torch.sigmoid(z)
print(y_pred)

tensor(0.9988, grad_fn=<SigmoidBackward0>)


In [18]:
loss=binary_cross_entropy_loss(y_pred, y)
print(loss)

tensor(6.7012, grad_fn=<NegBackward0>)


In [19]:
loss.backward()

In [21]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


## Using vector inputs
It is like creating a multi variable function.

In [22]:
x=torch.tensor([1.0,2.0,3.0], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [23]:
y=(x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [24]:
y.backward()

In [25]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

## Clearing gradients

In [48]:
x=torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [49]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [50]:
y.backward()

In [51]:
x.grad

tensor(4.)

In [53]:
x.grad.zero_() 
# This function clears the gradient after each pass 
# and doesn't let it accumulate

tensor(0.)

## Disable gradient tracking
Used to reduce unnecessary memory consumption when gradient tracking is not required.

### Method 1

In [55]:
x.requires_grad_(False)
x

tensor(2.)

In [56]:
y=x**2
y

tensor(4.)

In [58]:
# y.backward() 
# This doesn't work now

### Method 2

In [5]:
x=torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [6]:
z=x.detach()
z

tensor(2.)

In [7]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [8]:
y1=z**2
y1

tensor(4.)

In [23]:
y.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [25]:
# y1.backward() is NOT feasible

## Method 3

In [26]:
x=torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [28]:
with torch.no_grad():
    y=x**2

y

tensor(4.)

In [30]:
# y.backward() does NOT work

# Training Pipeline

In [6]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [8]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [10]:
df.shape

(569, 33)

In [11]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [12]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train, test, split

In [13]:
X_train, X_test, y_train, y_test=train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

Scaling

In [14]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [15]:
X_train

array([[ 1.15004913,  0.18687843,  1.11783855, ...,  1.20640787,
         0.2953048 ,  0.00733342],
       [ 1.50836359, -0.07408966,  1.51968395, ...,  1.27962342,
         0.13935809,  0.86457473],
       [ 0.56778814, -0.75792268,  0.57798563, ...,  0.16766224,
         0.44304378,  0.33243711],
       ...,
       [ 0.53979482,  0.10713818,  0.48868665, ...,  0.57797439,
        -0.38265299, -1.08055578],
       [ 1.08846384, -0.56944574,  1.03259861, ...,  0.60085425,
        -0.06747649, -0.07119669],
       [-0.77869041, -0.39546702, -0.79437731, ..., -0.41379127,
         0.14756581, -0.33479428]], shape=(455, 30))

In [16]:
y_train

6      M
300    M
375    B
4      M
204    B
      ..
180    M
216    B
75     M
444    M
410    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [17]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [18]:
y_train

array([1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,

Numpy arrays to PyTorch tensors

In [22]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [26]:
X_train_tensor.shape

torch.Size([455, 30])

In [24]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [34]:
class MySimpleNN():
    def __init__(self,X):
        
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64, requires_grad=True) 
        self.bias=torch.zeros(1,dtype=torch.float64, requires_grad=True) 

    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon=1e-7
        y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

        # Calculate loss
        loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss

Important Parameters

In [29]:
learning_rate=0.1
epochs=25

Training Pipeline

In [36]:
# Create  model
model=MySimpleNN(X_train_tensor)
# define loop
for epoch in range(epochs):
    # forward pass
    y_pred=model.forward(X_train_tensor)
  
    # loss calculation
    loss=model.loss_function(y_pred, y_train_tensor)
  
    # backward pass
    loss.backward()
  
    # parameters updation
    with torch.no_grad():
        model.weights-=learning_rate*model.weights.grad
        model.bias-=learning_rate*model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    #print loss in each epoch
    print(f"Epoch:{epoch+1}, Loss:{loss.item()}")


Epoch:1, Loss:3.6712012537005134
Epoch:2, Loss:3.5497589704549206
Epoch:3, Loss:3.4226307540113026
Epoch:4, Loss:3.291172831725925
Epoch:5, Loss:3.1577042294362863
Epoch:6, Loss:3.020434964124836
Epoch:7, Loss:2.8795490593367408
Epoch:8, Loss:2.7331618130224364
Epoch:9, Loss:2.5825500301677238
Epoch:10, Loss:2.4294229333857102
Epoch:11, Loss:2.265089153891582
Epoch:12, Loss:2.1020579156429844
Epoch:13, Loss:1.9411761693159475
Epoch:14, Loss:1.7781429865746272
Epoch:15, Loss:1.6181811759299705
Epoch:16, Loss:1.466240475820269
Epoch:17, Loss:1.32403009806631
Epoch:18, Loss:1.1972946262056128
Epoch:19, Loss:1.0879000070149991
Epoch:20, Loss:0.9969500818398143
Epoch:21, Loss:0.9244461107881833
Epoch:22, Loss:0.8691568192431701
Epoch:23, Loss:0.8287436683704242
Epoch:24, Loss:0.8001576173948709
Epoch:25, Loss:0.7802262175269037


In [37]:
model.weights

tensor([[-0.0529],
        [-0.1018],
        [ 0.2438],
        [ 0.3384],
        [ 0.1038],
        [-0.3074],
        [-0.2784],
        [ 0.1603],
        [-0.0094],
        [ 0.6117],
        [ 0.2841],
        [ 0.5893],
        [ 0.0850],
        [-0.2781],
        [-0.1504],
        [ 0.1265],
        [ 0.3230],
        [-0.4202],
        [-0.1496],
        [ 0.3919],
        [-0.1169],
        [-0.1109],
        [ 0.0168],
        [ 0.2460],
        [ 0.3943],
        [-0.2457],
        [-0.2925],
        [ 0.0629],
        [ 0.2323],
        [-0.2554]], dtype=torch.float64, requires_grad=True)

In [38]:
model.bias

tensor([-0.1307], dtype=torch.float64, requires_grad=True)

Evaluation

In [46]:
# model evaluation
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.99).float()
    accuracy=(y_pred==y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5964912176132202
