In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

print(np.__version__)

2.2.6


In [13]:
import numpy as np

# 0D Array
print("This is a 0D Array: ")
a = np.array(42)
print(a)
print("")

# 1D Array
print("This is a 1D Array: ")
b = np.array([1, 2, 3, 4, 5])
print(b)
print("")

# 2D Array
print("This is a 2D Array: ")
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print("")

# 3D Array
print("This is a 3D Array: ")
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d)

This is a 0D Array: 
42

This is a 1D Array: 
[1 2 3 4 5]

This is a 2D Array: 
[[1 2 3]
 [4 5 6]]

This is a 3D Array: 
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
# ndim attribute that returns an integer that tells us 
# how many dimensions the array have.
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [20]:
# When the array is created, 
# you can define the number of dimensions by using the ndmin argument.
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print(f"Number of dimensions: {arr.ndim}")

[[[[[1 2 3 4]]]]]
Number of dimensions: 5


In [21]:
# Indexing:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [24]:
a = np.array([1, 2, 3, 4])
print(a.dtype)
b = np.array(['apple', 'banana', 'cherry'])
print(b.dtype)

int64
<U6


In [25]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [26]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [28]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [31]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [30]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [32]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [2]:
# np.nditer() flattens the array into a 1D iterator
# that yields each scalar element
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


In [5]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)


np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [11]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [13]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [15]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

a = np.hstack((arr1, arr2)) # Stacking along rows
b = np.vstack((arr1, arr2)) # Stacking along columns
c = np.dstack((arr1, arr2)) # Stacking Along Height (depth)

print(a)
print(b)
print(c)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [21]:
Z = np.arange(10,50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [22]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.67652226 0.80211826 0.02474784]
  [0.62563335 0.0496513  0.98552724]
  [0.66952749 0.56285695 0.46931566]]

 [[0.91134556 0.89982804 0.19004118]
  [0.71934262 0.41956789 0.42111193]
  [0.21577396 0.834784   0.22377523]]

 [[0.2788212  0.3938709  0.16655661]
  [0.7600495  0.43086526 0.44453558]
  [0.06072344 0.33518398 0.34216448]]]


In [36]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0107158599378806 0.9964225153820997


In [39]:
Z = np.random.random(30)
m = Z.mean()
print(f"{Z} \n {m}")

[0.19349858 0.91930169 0.44038819 0.02097593 0.3894964  0.46174942
 0.49403908 0.0368443  0.83196601 0.97015685 0.54353483 0.32556453
 0.50523028 0.25218921 0.9687397  0.48076748 0.65144779 0.52431906
 0.07402641 0.21568291 0.93749682 0.11829105 0.96409735 0.12973803
 0.32138054 0.80590914 0.36100653 0.128337   0.46298168 0.17794511] 
 0.45690339660210216


In [40]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


In [44]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
